package com.bimoraai.brahm.ui.kundali

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.bimoraai.brahm.core.data.UserRepository
import com.bimoraai.brahm.core.network.ApiService
import com.bimoraai.brahm.core.network.KundaliRequest
import com.bimoraai.brahm.core.network.SaveKundaliRequest
import com.bimoraai.brahm.core.network.UserDto
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import javax.inject.Inject

data class KundaliSettings(
    val ayanamsha: String = "lahiri",   // lahiri | raman | kp | true_citra
    val rahuMode: String  = "mean",     // mean | true
    val nameLang: String  = "vedic",    // vedic | en
)

@HiltViewModel
class KundaliViewModel @Inject constructor(
    private val api: ApiService,
    private val userRepository: UserRepository,
) : ViewModel() {

    private val _kundali    = MutableStateFlow<Map<String, Any?>?>(null)
    private val _isLoading  = MutableStateFlow(false)
    private val _error      = MutableStateFlow<String?>(null)
    private val _settings   = MutableStateFlow(KundaliSettings())

    val kundali:    StateFlow<Map<String, Any?>?> = _kundali.asStateFlow()
    val isLoading:  StateFlow<Boolean>            = _isLoading.asStateFlow()
    val error:      StateFlow<String?>            = _error.asStateFlow()
    val settings:   StateFlow<KundaliSettings>    = _settings.asStateFlow()
    val savedProfile: StateFlow<UserDto?>         = userRepository.user

    // Prevent auto-regeneration after explicit user action or settings change
    var hasAutoGenerated = false
        private set

    init {
        // Try to load saved kundali from backend first
        viewModelScope.launch {
            try {
                val res = api.getSavedKundali()
                if (res.isSuccessful) {
                    val body = res.body()
                    val found = body?.get("found")?.let { (it as? JsonPrimitive)?.contentOrNull == "true" || it.toString() == "true" } ?: false
                    if (found) {
                        val kundaliObj = body?.get("kundali") as? JsonObject
                        val kundaliJsonStr = kundaliObj?.get("kundali_json")?.let { (it as? JsonPrimitive)?.contentOrNull }
                        if (!kundaliJsonStr.isNullOrBlank()) {
                            val parsed = kotlinx.serialization.json.Json.parseToJsonElement(kundaliJsonStr)
                            if (parsed is JsonObject) {
                                val loadedData = jsonObjectToMap(parsed)
                                // Pre-fill inputs from saved kundali metadata
                                kundaliObj?.let { k ->
                                    name  = (k["label"] as? JsonPrimitive)?.contentOrNull ?: ""
                                    dob   = (k["birth_date"] as? JsonPrimitive)?.contentOrNull ?: ""
                                    tob   = (k["birth_time"] as? JsonPrimitive)?.contentOrNull ?: ""
                                    pob   = (k["birth_place"] as? JsonPrimitive)?.contentOrNull ?: ""
                                    lat   = (k["birth_lat"] as? JsonPrimitive)?.contentOrNull?.toDoubleOrNull() ?: 0.0
                                    lon   = (k["birth_lon"] as? JsonPrimitive)?.contentOrNull?.toDoubleOrNull() ?: 0.0
                                    tz    = (k["birth_tz"] as? JsonPrimitive)?.contentOrNull ?: "5.5"
                                }
                                // Check if saved kundali has antardashas in the first dasha entry
                                @Suppress("UNCHECKED_CAST")
                                val firstDasha = (loadedData["dashas"] as? List<*>)
                                    ?.firstOrNull() as? Map<*, *>
                                val hasAntardashas = firstDasha?.containsKey("antardashas") == true
                                // Regenerate if missing shadbala, ashtakavarga, or antardashas (stale save)
                                val isStale = !loadedData.containsKey("shadbala")
                                    || !loadedData.containsKey("ashtakavarga")
                                    || !hasAntardashas
                                if (isStale && name.isNotBlank() && dob.isNotBlank()) {
                                    _kundali.value = loadedData  // Show existing data while regenerating
                                    hasAutoGenerated = true
                                    generate()  // Regenerate in background to get fresh data
                                } else {
                                    _kundali.value = loadedData
                                    hasAutoGenerated = true  // Mark as loaded so LaunchedEffect won't regenerate
                                }
                            }
                        }
                    }
                }
            } catch (_: Exception) { /* Ignore — will fall back to profile auto-gen */ }
        }
    }

    // Birth inputs — kept for recalculate after settings change
    private var name = ""; private var dob = ""; private var tob = ""
    private var pob  = ""; private var lat = 0.0; private var lon = 0.0; private var tz = "5.5"

    fun setInputs(name: String, dob: String, tob: String, pob: String, lat: Double, lon: Double, tz: String = "5.5") {
        this.name = name; this.dob = dob; this.tob = tob
        this.pob  = pob;  this.lat = lat; this.lon = lon; this.tz = tz
    }

    fun updateSettings(s: KundaliSettings) {
        _settings.value = s
        if (_kundali.value != null) generate()   // recalculate
    }

    fun generate(isAutoFromProfile: Boolean = false) {
        if (isAutoFromProfile) hasAutoGenerated = true
        viewModelScope.launch {
            _isLoading.value = true
            _error.value     = null
            try {
                val s = _settings.value
                val res = api.generateKundali(KundaliRequest(
                    name      = name,
                    date      = dob,
                    time      = tob,
                    place     = pob,
                    lat       = lat,
                    lon       = lon,
                    tz        = tz.toDoubleOrNull() ?: 5.5,
                    ayanamsha = s.ayanamsha,
                    rahu_mode = s.rahuMode,
                ))
                if (res.isSuccessful) {
                    val data = res.body()?.let { jsonObjectToMap(it) } as? Map<String, Any?>
                    _kundali.value = data
                    // Save to backend in background
                    if (data != null) {
                        launch {
                            try {
                                api.saveKundali(SaveKundaliRequest(
                                    name        = name,
                                    birth_date  = dob,
                                    birth_time  = tob,
                                    birth_lat   = lat,
                                    birth_lon   = lon,
                                    birth_tz    = tz.toDoubleOrNull() ?: 5.5,
                                    birth_place = pob,
                                    kundali_json = res.body()!!.toString(),
                                ))
                            } catch (_: Exception) { /* Non-critical */ }
                        }
                    }
                } else {
                    _error.value = "Failed to generate Kundali"
                }
            } catch (e: Exception) {
                _error.value = e.message ?: "Network error"
            } finally {
                _isLoading.value = false
            }
        }
    }
}

internal fun jsonElementToAny(element: JsonElement): Any? = when (element) {
    is JsonPrimitive -> element.contentOrNull
    is JsonArray     -> element.map { jsonElementToAny(it) }
    is JsonObject    -> jsonObjectToMap(element)
    else             -> null
}

internal fun jsonObjectToMap(obj: JsonObject): Map<String, Any?> =
    obj.entries.associate { (k, v) -> k to jsonElementToAny(v) }
