package com.bimoraai.brahm.ui.kundali

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.bimoraai.brahm.core.data.UserRepository
import com.bimoraai.brahm.core.network.ApiService
import com.bimoraai.brahm.core.network.KundaliRequest
import com.bimoraai.brahm.core.network.SaveKundaliRequest
import com.bimoraai.brahm.core.network.UserDto
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import javax.inject.Inject

data class KundaliSettings(
    val ayanamsha: String = "lahiri",   // lahiri | raman | kp | true_citra
    val rahuMode: String  = "mean",     // mean | true
    val nameLang: String  = "vedic",    // vedic | en
)

@HiltViewModel
class KundaliViewModel @Inject constructor(
    private val api: ApiService,
    private val userRepository: UserRepository,
) : ViewModel() {

    private val _kundali    = MutableStateFlow<Map<String, Any?>?>(null)
    private val _isLoading  = MutableStateFlow(false)
    private val _error      = MutableStateFlow<String?>(null)
    private val _settings   = MutableStateFlow(KundaliSettings())

    val kundali:    StateFlow<Map<String, Any?>?> = _kundali.asStateFlow()
    val isLoading:  StateFlow<Boolean>            = _isLoading.asStateFlow()
    val error:      StateFlow<String?>            = _error.asStateFlow()
    val settings:   StateFlow<KundaliSettings>    = _settings.asStateFlow()
    val savedProfile: StateFlow<UserDto?>         = userRepository.user

    // Prevent auto-regeneration after explicit user action or settings change
    var hasAutoGenerated = false
        private set

    init {
        // Use cached kundali JSON from UserRepository (pre-fetched at login) — instant load
        viewModelScope.launch {
            try {
                val kundaliJsonStr = userRepository.kundaliJson.value
                    ?: run {
                        // Cache miss (first ever launch) — fetch directly
                        val res = api.getSavedKundali()
                        if (res.isSuccessful) {
                            val body = res.body()
                            val found = body?.get("found")?.let {
                                (it as? JsonPrimitive)?.contentOrNull == "true" || it.toString() == "true"
                            } ?: false
                            if (found) {
                                val kundaliObj = body?.get("kundali") as? JsonObject
                                kundaliObj?.get("kundali_json")?.let { (it as? JsonPrimitive)?.contentOrNull }
                            } else null
                        } else null
                    }

                if (!kundaliJsonStr.isNullOrBlank()) {
                    val parsed = Json.parseToJsonElement(kundaliJsonStr)
                    if (parsed is JsonObject) {
                        val loadedData = jsonObjectToMap(parsed)
                        // Pre-fill birth inputs from UserRepository profile
                        userRepository.user.value?.let { u ->
                            name = u.name
                            dob  = u.date
                            tob  = u.time
                            pob  = u.place
                            lat  = u.lat
                            lon  = u.lon
                            tz   = u.tz.toString()
                        }
                        @Suppress("UNCHECKED_CAST")
                        val firstDasha  = (loadedData["dashas"] as? List<*>)?.firstOrNull() as? Map<*, *>
                        @Suppress("UNCHECKED_CAST")
                        val vargaCharts = loadedData["varga_charts"] as? Map<*, *>
                        val isStale = !loadedData.containsKey("shadbala")
                            || !loadedData.containsKey("ashtakavarga")
                            || !loadedData.containsKey("upagraha")
                            || firstDasha?.containsKey("antardashas") != true
                            || vargaCharts?.containsKey("D-3") != true
                        _kundali.value = loadedData
                        hasAutoGenerated = true
                        if (isStale && name.isNotBlank() && dob.isNotBlank()) generate()
                    }
                }
            } catch (_: Exception) { /* Fall back to profile auto-gen */ }
        }
    }

    // Birth inputs — kept for recalculate after settings change
    private var name = ""; private var dob = ""; private var tob = ""
    private var pob  = ""; private var lat = 0.0; private var lon = 0.0; private var tz = "5.5"

    fun setInputs(name: String, dob: String, tob: String, pob: String, lat: Double, lon: Double, tz: String = "5.5") {
        this.name = name; this.dob = dob; this.tob = tob
        this.pob  = pob;  this.lat = lat; this.lon = lon; this.tz = tz
    }

    fun updateSettings(s: KundaliSettings) {
        _settings.value = s
        if (_kundali.value != null) generate()   // recalculate
    }

    fun generate(isAutoFromProfile: Boolean = false) {
        if (isAutoFromProfile) hasAutoGenerated = true
        viewModelScope.launch {
            _isLoading.value = true
            _error.value     = null
            try {
                val s = _settings.value
                val res = api.generateKundali(KundaliRequest(
                    name      = name,
                    date      = dob,
                    time      = tob,
                    place     = pob,
                    lat       = lat,
                    lon       = lon,
                    tz        = tz.toDoubleOrNull() ?: 5.5,
                    ayanamsha = s.ayanamsha,
                    rahu_mode = s.rahuMode,
                ))
                if (res.isSuccessful) {
                    val data = res.body()?.let { jsonObjectToMap(it) } as? Map<String, Any?>
                    _kundali.value = data
                    // Save to backend + update cache
                    if (data != null) {
                        val rawJson = res.body()!!.toString()
                        userRepository.cacheKundaliJson(rawJson)  // instant cache for next open
                        launch {
                            try {
                                api.saveKundali(SaveKundaliRequest(
                                    name        = name,
                                    birth_date  = dob,
                                    birth_time  = tob,
                                    birth_lat   = lat,
                                    birth_lon   = lon,
                                    birth_tz    = tz.toDoubleOrNull() ?: 5.5,
                                    birth_place = pob,
                                    kundali_json = rawJson,
                                ))
                            } catch (_: Exception) { /* Non-critical */ }
                        }
                    }
                } else {
                    _error.value = "Failed to generate Kundali"
                }
            } catch (e: Exception) {
                _error.value = e.message ?: "Network error"
            } finally {
                _isLoading.value = false
            }
        }
    }
}

internal fun jsonElementToAny(element: JsonElement): Any? = when (element) {
    is JsonPrimitive -> element.contentOrNull
    is JsonArray     -> element.map { jsonElementToAny(it) }
    is JsonObject    -> jsonObjectToMap(element)
    else             -> null
}

internal fun jsonObjectToMap(obj: JsonObject): Map<String, Any?> =
    obj.entries.associate { (k, v) -> k to jsonElementToAny(v) }
