"""
Deploy kundali.py to VM
Run on VM: python deploy_kundali.py
This creates src/special/kundali.py with the correct content.
"""
import os
import base64
import zlib

# Compressed + base64 encoded kundali.py
# Generated by deploy script - DO NOT EDIT manually
DATA = ""
# This will be filled by the local build script

def main():
    target_dir = os.path.expanduser("~/books/src/special")
    os.makedirs(target_dir, exist_ok=True)

    # Also create __init__.py
    init_path = os.path.join(target_dir, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, 'w') as f:
            f.write("# Brahm AI - Special Calculation Modules\n")
            f.write("# These modules use astronomical computation (NOT RAG)\n")
            f.write("# NASA DE441 + Swiss Ephemeris for extreme accuracy\n")

    target_path = os.path.join(target_dir, "kundali.py")

    if DATA:
        content = zlib.decompress(base64.b64decode(DATA)).decode('utf-8')
        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[OK] Written: {target_path}")
        print(f"     Size: {os.path.getsize(target_path)} bytes")
    else:
        print("[ERROR] No data embedded. Run build script first.")

if __name__ == "__main__":
    main()
